=encoding utf8

=head1 NAME

Aobabot - 슬랙 봇

=head1 SYNOPSIS

=begin HTML
<img src="https://pbs.twimg.com/media/Cs7J0NTVMAAEavT.jpg:large">
=end HTML

    # 저장소 클론
    $ git clone https://github.com/unstabler/aobabot.git
    # 의존 모듈 설치 (cpanm 필요)
    $ cpanm installdeps
    # 설정 파일 복사하고 편집하기
    $ cp config.json.sample config.json
    # 아오바 봇 실행
    $ perl aobabot.pl

=head1 LICENSE

이 소프트웨어는 Perl의 라이선스인 Artistic License를 따릅니다.
해당 라이선스의 전문은 L<http://dev.perl.org/licenses/artistic.html>를 참조하십시오.

=head1 AUTHOR

UNSTABLER (Gyuhwan Park) <doping.cheese@gmail.com>
